# Generated by Django 4.1.4 on 2023-01-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_laboral', '0004_post_actividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Bolsa Laboral', 'verbose_name_plural': 'Bolsa Laboral'},
        ),
        migrations.AlterModelOptions(
            name='post_actividades',
            options={'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='post_beneficios',
            options={'verbose_name': 'Beneficios', 'verbose_name_plural': 'Beneficios'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
