# Generated by Django 4.1.4 on 2023-01-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_laboral', '0005_alter_post_options_alter_post_actividades_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Bolsa_laboral',
        ),
    ]
