# Generated by Django 4.1.4 on 2023-01-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_laboral', '0006_rename_post_bolsa_laboral'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_beneficios',
            new_name='Beneficios',
        ),
    ]
