# Generated by Django 4.1.4 on 2023-01-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolsa_laboral', '0007_rename_post_beneficios_beneficios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_actividades',
            new_name='Actividades',
        ),
    ]
