# Generated by Django 4.1.2 on 2022-11-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carrera',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
