# Generated by Django 4.1.2 on 2022-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_profile_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
