# Generated by Django 4.1.2 on 2022-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_profile_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nombres',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
