# Generated by Django 4.1.2 on 2022-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_profile_apellidos_profile_lat_profile_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
