# Generated by Django 4.1.2 on 2022-11-08 10:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cargo_actual',
            field=models.CharField(choices=[('Emprendedor o socio de mi empresa', 'Emprendedor o socio de mi empresa'), ('Cargo directivo o gerencial', 'Cargo directivo o gerencial'), ('Cargo subgerente o jefe de departamento', 'Cargo subgerente o jefe de departamento'), ('Profesional con trabajadores a cargo', 'Profesional con trabajadores a cargo'), ('Profesional sin trabajadores a cargo', 'Profesional sin trabajadores a cargo'), ('Independiente (freelance)', 'Independiente (freelance)'), ('No me encuentro trabajando', 'No me encuentro trabajando')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='continuidad_estudios',
            field=models.CharField(blank=True, choices=[('Si', 'Sí'), ('No', 'No'), ('Actualmente me encuentro estudiando', 'Actualmente me encuentro estudiando')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dominio_ingles',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='grado_maximo',
            field=models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Diplomado', 'Diplomado'), ('Doctorado', 'Doctorado'), ('Podtdoctorado', 'Postdoctorado')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ingresos',
            field=models.CharField(blank=True, choices=[('$0 a $500.000', '$0 a $500.000'), ('$500.001 a $1.000.000', '$500.001 a $1.000.000'), ('$1.000.001 a $1.500.000 ', '$1.000.001 a $1.500.000'), ('$1.500.001 a $2.000.000', '$1.500.001 a $2.000.000'), ('$2.000.001 a $2.500.000', '$2.000.001 a $2.500.000'), ('$2.500.001 a $3.000.000', '$2.500.001 a $3.000.000'), ('Más de $3.000.000', 'mas de $3.000.000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='movilidad_ucn',
            field=models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nivel_ingles',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='primer_empleo',
            field=models.CharField(blank=True, choices=[('Entre 0 y 3 meses', 'Entre 0 y 3 meses'), ('Entre 3 y 6 meses', 'Entre 3 y 6 meses'), ('Entre 6 meses y 1 año', 'Entre 6 meses y 1 año'), ('Más de 1 año', 'Mas de 1 año'), ('Aún no encuentro mi primer empleo', 'Aún no encuentro mi primer empleo')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='programas_interes',
            field=models.CharField(blank=True, choices=[('Magisteres', 'Magisteres'), ('Doctorados', 'Doctorados'), ('Bootcamps', 'Bootcamps'), ('Ninguno', 'Ninguno')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sector_trabajo',
            field=models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado'), ('Social', 'Social'), ('No me encuentro trabajando', 'No me encuentro trabajando')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='titulado',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='carrera',
            field=models.CharField(blank=True, choices=[('IICG', 'IICG'), ('INGECO', 'INGECO')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lng',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='situacion_laboral',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Desempleado', 'Desempleado'), ('Empleado buscando otro trabajo', 'Empleado buscando otro trabajo'), ('No deseo ejercer', 'No deseo ejercer')], max_length=200, null=True),
        ),
    ]
