# Generated by Django 4.1.3 on 2022-11-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_remove_profile_nivel_ingles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carrera',
            field=models.CharField(blank=True, choices=[('IICG', 'Ingeniería en Información y Control de Gestión'), ('INGECO', 'Ingeniería Comercial')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grado_maximo',
            field=models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Diplomado', 'Diplomado'), ('Magíster', 'Magíster'), ('Doctorado', 'Doctorado'), ('Podtdoctorado', 'Postdoctorado')], max_length=200, null=True),
        ),
    ]
