# Generated by Django 4.1.3 on 2022-11-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_alter_profile_fecha_egreso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='movilidad_ucn',
            new_name='interes_colaboracion',
        ),
        migrations.AddField(
            model_name='profile',
            name='oferta_eciem',
            field=models.CharField(blank=True, choices=[('Magíster en Administración', 'Magíster en Administración'), ('Magíster en Ciencias Empresariales con Mención Emprendimiento', 'Magíster en Ciencias Empresariales con Mención Emprendimiento')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_colaboracion',
            field=models.CharField(blank=True, choices=[('Ofrecer puestos de trabajo a egresados', 'Ofrecer puestos de trabajo a egresados'), ('Ofrecer beneficios/descuentos a egresados', 'Ofrecer beneficios/descuentos a egresados'), ('Impartir cursos o talleres sobre inserción laboral', 'Impartir cursos o talleres sobre inserción laboral'), ('Impartir cursos o talleres sobre alguna especialidad', 'Impartir cursos o talleres sobre alguna especialidad'), ('Organizar eventos para egresados', 'Organizar eventos para egresados')], max_length=200, null=True),
        ),
    ]
