# Generated by Django 4.1.3 on 2022-11-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_rename_movilidad_ucn_profile_interes_colaboracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo_colaboracion',
            field=models.CharField(blank=True, choices=[('Ofrecer puestos de trabajo a egresados', 'Ofrecer puestos de trabajo a egresados'), ('Ofrecer beneficios/descuentos a egresados', 'Ofrecer beneficios/descuentos a egresados'), ('Impartir cursos o talleres sobre inserción laboral', 'Impartir cursos o talleres sobre inserción laboral'), ('Impartir cursos o talleres sobre alguna especialidad', 'Impartir cursos o talleres sobre alguna especialidad'), ('Organizar eventos para egresados', 'Organizar eventos para egresados'), ('Ninguna', 'Ninguna')], max_length=200, null=True),
        ),
    ]
