# Generated by Django 4.1.3 on 2022-12-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_forma_colaboracion_desicion_colaboracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desicion_colaboracion',
            name='desicion_c',
        ),
        migrations.RemoveField(
            model_name='desicion_colaboracion',
            name='user',
        ),
        migrations.DeleteModel(
            name='Area_interes',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Desicion_colaboracion',
        ),
        migrations.DeleteModel(
            name='Forma_colaboracion',
        ),
    ]
