# Generated by Django 4.1.3 on 2022-12-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0016_remove_desicion_colaboracion_desicion_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area_interes',
            field=models.CharField(choices=[('Administración', 'Administración'), ('Recursos humanos', 'Recursos humanos'), ('Marketing', 'Marketing'), ('Contabilidad', 'Contabilidad'), ('Finanzas', 'Finanzas'), ('Control de Gestión', 'Control de Gestión'), ('Análisis de datos', 'Análisis de datos'), ('TI (python, excel, R, Stata, Bizagi, entre otros)', 'TI (python, excel, R, Stata, Bizagi, entre otros)')], max_length=200, null=True),
        ),
    ]
