# Generated by Django 4.1.4 on 2023-01-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0017_profile_area_interes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='area_interes',
            field=models.CharField(choices=[('Administración', 'Administración'), ('Recursos humanos', 'Recursos humanos'), ('Marketing', 'Marketing'), ('Contabilidad', 'Contabilidad'), ('Finanzas', 'Finanzas'), ('Control de Gestión', 'Control de Gestión'), ('Análisis de datos', 'Análisis de datos'), ('TI (python, excel, R, Stata, Bizagi, entre otros)', 'TI (python, excel, R, Stata, Bizagi, entre otros)')], max_length=200, null=True, verbose_name='Área Interés'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='programas_interes',
            field=models.CharField(blank=True, choices=[('Talleres', 'Talleres'), ('Cursos', 'Cursos'), ('Magísteres', 'Magísteres'), ('Doctorados', 'Doctorados'), ('Ninguno', 'Ninguno')], max_length=200, null=True, verbose_name='Programas Interés'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='situacion_laboral',
            field=models.CharField(blank=True, choices=[('Empleado', 'Empleado'), ('Desempleado', 'Desempleado'), ('Empleado buscando otro trabajo', 'Empleado buscando otro trabajo'), ('No deseo ejercer', 'No deseo ejercer')], max_length=200, null=True, verbose_name='Situación Laboral'),
        ),
    ]
